// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using proyectogranja1.Data;

#nullable disable

namespace proyectogranja1.Migrations
{
    [DbContext(typeof(proyectogranja1Context))]
    [Migration("20251122164056_n1")]
    partial class n1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("proyectogranja1.Models.Distribucion", b =>
                {
                    b.Property<int>("DistribucionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DistribucionID"));

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("EmpleadoID")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("LitrosEntregados")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("DistribucionID");

                    b.HasIndex("EmpleadoID");

                    b.ToTable("Distribucion");
                });

            modelBuilder.Entity("proyectogranja1.Models.Empleado", b =>
                {
                    b.Property<int>("EmpleadoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmpleadoID"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("CI")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Cargo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("EsVeterinario")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("EmpleadoID");

                    b.ToTable("Empleado");
                });

            modelBuilder.Entity("proyectogranja1.Models.Produccion", b =>
                {
                    b.Property<int>("ProduccionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProduccionID"));

                    b.Property<string>("Calidad")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("EmpleadoID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalLitros")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("VacaID")
                        .HasColumnType("integer");

                    b.HasKey("ProduccionID");

                    b.HasIndex("EmpleadoID");

                    b.HasIndex("VacaID");

                    b.ToTable("Produccion");
                });

            modelBuilder.Entity("proyectogranja1.Models.Vaca", b =>
                {
                    b.Property<int>("VacaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VacaID"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("CodigoVaca")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("EstadoSalud")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Raza")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("VacaID");

                    b.ToTable("Vaca");
                });

            modelBuilder.Entity("proyectogranja1.Models.Distribucion", b =>
                {
                    b.HasOne("proyectogranja1.Models.Empleado", "Empleado")
                        .WithMany("Distribuciones")
                        .HasForeignKey("EmpleadoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("proyectogranja1.Models.Produccion", b =>
                {
                    b.HasOne("proyectogranja1.Models.Empleado", "Empleado")
                        .WithMany("Producciones")
                        .HasForeignKey("EmpleadoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("proyectogranja1.Models.Vaca", "Vaca")
                        .WithMany("Producciones")
                        .HasForeignKey("VacaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Vaca");
                });

            modelBuilder.Entity("proyectogranja1.Models.Empleado", b =>
                {
                    b.Navigation("Distribuciones");

                    b.Navigation("Producciones");
                });

            modelBuilder.Entity("proyectogranja1.Models.Vaca", b =>
                {
                    b.Navigation("Producciones");
                });
#pragma warning restore 612, 618
        }
    }
}
